# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration

ENV["RAILS_ENV"] = "test"

require 'devise'
require "rails_app/config/environment"
require 'rspec/rails'


#ActiveRecord::Base.logger = Logger.new(STDOUT)
ActiveRecord::Base.establish_connection YAML.load_file('./spec/rails_app/config/database.yml')['test']
c = ActiveRecord::Base.connection
c.create_table :users, force: true do |t|
  t.string :email
  t.string :encrypted_password
  t.timestamps null: false
end
c.create_table :authentications, force: true do |t|
  t.references :resource, polymorphic: true
  t.string :uid,              null: false
  t.string :provider,         null: false
  t.string :access_token
  t.string :permissions
  t.timestamps null: false
end

RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  config.use_transactional_fixtures = true

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end
